namespace BankingApi.Models
{
    public class Account
    {
        public int AccountId { get; set; }  // Primary key (auto-generated by EF)

        // Foreign key to User (one-to-one relationship)
        public int UserId { get; set; }

        public decimal Balance { get; set; }

        // Navigation property to the related User
        public User User { get; set; }

        // Navigation property to related Transactions
        public ICollection<Transaction> Transactions { get; set; }
    }

}
