namespace BankingApi.Models
{
    public class Transaction
    {
        public int TransactionId { get; set; }  // Primary key (auto-generated by EF)
        public int AccountId { get; set; }  // Foreign key to Account table
        public string Type { get; set; }  // Transaction type (e.g., Deposit, Withdrawal)
        public decimal Amount { get; set; }  // Transaction amount
        public DateTime Date { get; set; }  // Transaction date

        // Navigation property to related Account
        public Account Account { get; set; }
    }
}
