namespace BankingApi.Models
{
    public class User
    {
        public int Id { get; set; }  // Primary key (auto-generated by EF)
        public string Name { get; set; }
        public string Password { get; set; }

        // Navigation property to the related Account
        public Account Account { get; set; }
    }
}
